name = "emby-worker-proxy"
main = "worker.js"
compatibility_date = "2026-03-06"
keep_vars = true

[[d1_databases]]
binding = "EMBY_D1"
database_name = "emby-proxy"
database_id = "76e45249-6dec-4af8-afc6-345a699474f6"
